{% set name = "gwpopulation" %}
{% set version = "1.2.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gwpopulation-{{ version }}.tar.gz
  sha256: 3d6f0c9e6a1e85102892551dff501ad4cea00fd69de0290a1c6cf4e2eede53be

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - wheel
  run:
    - wcosmo >=0.3.0
    - bilby >=2.2.0
    - numpy
    - python >={{ python_min }}
    - scipy
    - cached_interpolate >=0.3.0

test:
  requires:
    - python {{ python_min }}
    - astropy-base
    - pip
    - pytest
    - jax
    - numpyro
    - scipy <1.15
  source_files:
    - priors/
    - test/
  commands:
    # check metadata
    - python -m pip check
    - python -m pip show gwpopulation
    # run test suite
    - python -m pytest -ra test/

about:
  home: https://github.com/ColmTalbot/gwpopulation
  summary: Unified population inference
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - ColmTalbot
